### ISSUE TITLE
Add your chapter to our listings

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/tokyo#3]
Once issues #1 & #2 are complete, please complete Step 5 in the [chapter setup instructions](https://github.com/ProtoSchool/organizing#how-to-start-a-new-protoschool-chapter) by opening a pull request to have your chapter included in the [list of ProtoSchool chapters](https://proto.school/#/chapters).

Please be sure to include the `repo` field so that your listing will link to this chapter repo. Should you decide that you'd like your listing to go to a website instead (now or in the future), you can add an additional `website` field with the appropriate URL, which will update the link.

**Comment by onion797jp** [comment]
[PR](https://github.com/ProtoSchool/protoschool.github.io/pull/297) created so closing this issue 👍
