### ISSUE TITLE
Question about the IPFS Tokyo Workshop

### ISSUE THREAD

**Issue by tiaguito** [ProtoSchool/tokyo#4]
Hello @onion797jp 

I would like to ask if the IPFS workshop in Tokyo is open for anybody and if we have to pay an entrance fee, or something similar.

**Comment by onion797jp** [comment]
Yes, IPFS workshop in Tokyo (Oct 12) is open for anybody and free.
Registration is recommended from here:
https://neutrino.connpass.com/event/148341/

**Comment by tiaguito** [comment]
Thank you
